### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by orourkedd** [orourkedd/effects-as-data-universal#1]
There is documentation for the various actions in `effects-as-data@1` here: https://github.com/orourkedd/effects-as-data#actions-packaged-with-effects-as-data.  These examples need to be updated to `effects-as-data@2` and moved into the `effects-as-data-universal` repo

**Comment by ps-video-player** [comment]
Use https://github.com/orourkedd/effects-as-data/blob/01065c650c0ae10b9c42b652e706fa03e75e7a38/README.md

Add `call`, `either`, `retry` and `setImmediate`
